##### 
Write a function so that the columns of the output matrix are powers of the input vector. 
 
The order of the powers is determined by the increasing boolean argument. Specifically, when increasing is False, the i-th output column is the input vector raised element-wise to the power of N - i - 1. 
 
 
HINT: Such a matrix with a geometric progression in each row is named for AlexandreTheophile Vandermonde. 

In [61]:
import numpy as np

def Vandermonde(in_matrix, n):
    m=len(in_matrix)
    out_matrix = np.array([x**(n-1-i) for x in in_matrix for i in range(n)]).reshape(m,n)
    return out_matrix

in_matrix=np.array([1,2,3,4,5])
n=5
Vandermonde(in_matrix,n)


array([[  1,   1,   1,   1,   1],
       [ 16,   8,   4,   2,   1],
       [ 81,  27,   9,   3,   1],
       [256,  64,  16,   4,   1],
       [625, 125,  25,   5,   1]])

In [62]:
np.vander(in_matrix,n)

array([[  1,   1,   1,   1,   1],
       [ 16,   8,   4,   2,   1],
       [ 81,  27,   9,   3,   1],
       [256,  64,  16,   4,   1],
       [625, 125,  25,   5,   1]])

##### 
Problem Statement 2: 
 
Given a sequence of n values x1, x2, ..., xn and a window size k>0, the k-th moving average of the given sequence is defined as follows: 
 
The moving average sequence has n-k+1 elements as shown below. 
 
The moving averages with k=4 of a ten-value sequence (n=10) is shown below 

i 1  2  3  4  5  6  7  8  9 10  ===== == == == == == == == == == == 
\Input 10 20 30 40 50 60 70 80 90 100 
y1      25 = (10+20+30+40)/4 
y2      35 = (20+30+40+50)/4 
y3      45 = (30+40+50+60)/4 
y4      55 = (40+50+60+70)/4
y5      65 = (50+60+70+80)/4
y6      75 = (60+70+80+90)/4 
y7      85 = (70+80+90+100)/4 

Write a function to find moving average in an array over a window:
Test it over [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150] and window of 3.

In [3]:
def moving_avg(array,window):
    for i in range(len(array)-window+1): # for loop over range of length of given array - windowsize
       # print(sum(array[i:window+i]))
        print('y'+str(i+1)+' = '+str(sum(array[i:window+i])/window))  #for every loop it execute sum of 3 items which divided y window size
    
a=np.array([3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150])

moving_avg(a,3)
        

y1 = 5.0
y2 = 4.666666666666667
y3 = 5.666666666666667
y4 = 6.666666666666667
y5 = 9.666666666666666
y6 = 28.666666666666668
y7 = 49.333333333333336
y8 = 72.66666666666667
y9 = 84.0
y10 = 93.33333333333333
y11 = 116.33333333333333


In [4]:
def moving_avg1(array,n):
    a=np.cumsum(array)
    a[n:]=a[n:]-a[:-n]
    return (a[n-1:]/n)
    
moving_avg1(a,3)    

array([  5.        ,   4.66666667,   5.66666667,   6.66666667,
         9.66666667,  28.66666667,  49.33333333,  72.66666667,
        84.        ,  93.33333333, 116.33333333])